### ISSUE TITLE
Spread out presence updates

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-appservice-discord#19]
Currently I'm seeing hundreds of presence updates every minute or so. It would be nice if this spike in load was spread out instead of being a spike.

**Comment by Half-Shot** [comment]
I can make it so that we can increase the interval at the cost of synapse flickering users between being online and offline (I'm aware that this already takes place to some extent, but the timeout is there to minify it).

I've brought this up before that bridged users shouldn't be timing out the same way regular users do in regards to presence, because this is a protocol/synapse issue really.

**Comment by Half-Shot** [comment]
Support for this has been added as part of the presence-handler branch

**Comment by Half-Shot** [comment]
This can now be configured in logging, but we still hardcode a minimum of 250ms between updates to keep it sensible.

**Comment by turt2live** [comment]
A nice fix for this would be https://github.com/matrix-org/synapse/issues/2385

**Comment by Half-Shot** [comment]
Yeah, would be. I guess this won't be a release blocker since it works with small guilds and or large homeservers. I think we be entirely boned without support for an enhanced presence system since the current one doesn't scale at all.

**Comment by Half-Shot** [comment]
I believe we actually spread this a bit now, i.e. you can configure it to do a user per N milliseconds.
