### ISSUE TITLE
D -> M webhook messages sometimes have wrong nickname

### ISSUE THREAD

**Issue by Sorunome** [Half-Shot/matrix-appservice-discord#256]
D -> M webhook messages have, on the matrix side, sometimes a wrong nickname. Haven't quite figured out the pattern yet

**Comment by MayhemBill** [comment]
I've experienced this, I have about 15 discord users bridge and only one of them doesn't have an avatar or a proper name. The only thing so far I've found that sets hers apart is she has a very long username. Most others are only about 5-15 chars and hers is about 30.

Otherwise no major difference in names.

**Comment by Sorunome** [comment]
fixed!
