### ISSUE TITLE
strip out matrix.to hyperlinks from mentions

### ISSUE THREAD

**Issue by ara4n** [Half-Shot/matrix-appservice-discord#652]
currently every Matrix mention causes a matrix.to link preview to unfurl in Discord.  This is partially due to https://github.com/matrix-org/matrix.to/issues/182, but presumably we should be mapping them to Discord mentions rather than leaking matrix.to URLs everywhere

**Comment by Sorunome** [comment]
They should be mapped to discord mentions, where possible.

**Comment by StepS-** [comment]
Discord mentions are not possible for matrix-only nicks since those are sent as webhooks -- they do not have a real sender. However, URLs can be wrapped in angular brackets < > to prevent an embed from generating. (This works inconsistently on Discord Mobile, though.)
An alternative, as linked in the issue, would be to prevent the embed from generating server-side by denying the info it needs to display it.

**Comment by vranki** [comment]
OK I made a hot fix:

change src/matrixeventprocessor.ts line 535

`https://matrix.to/#/${sender}`,    to      ``,

This removes URL from the event and prevents annoying URL previews on Discord side.

**Comment by eras** [comment]
Is there a particular reason why that could not just be the fix? It probably also filters room mentions, but I don't think it would be that bad, possibly even preferably.

What I'm suggesting is to implement this fix as-is and if later on some more refined control is desirable, reintroduce that as a later fix.
