### ISSUE TITLE
Could someone explain to me how this can be self-hosted and bridge matrix.org homeserver ?

### ISSUE THREAD

**Issue by lf94** [Half-Shot/matrix-appservice-discord#749]
As the title says. The documentation trips me up when I read this:

Modify your HSs appservices config so that it includes the generated file.

Which makes me think I have to also host a homeserver in order to use this bridge, so that the bot can run on it, and then connect to matrix.org homeserver and discord at the same time (so 3 connections).

Is this a correct understanding?

Thank you!

**Comment by FSG-Cat** [comment]
All appservices have to run with HS colaboration. 

And Appservice Puppets are just users that are controlled by the Appservice and they federate like normal users. 

So your question doesnt rly make sense to me but thats because im thinking at way to high a level. Yes you would have your homeserver talk to matrix.org and your homeserver would talk to your Appservice discord instance and that Appservice discord instance would talk to discord.com and the bot user on discord.com

**Comment by lf94** [comment]
Ok cool, thank you :) This could be made more clear in the README.

**Comment by FSG-Cat** [comment]
I fail to see how this should be more clear in the README due to how this is a fundemental of how all Appservices works and therefore anyone who is looking at hosting them should have this understaning already is an argument that can be made.
